# Generated by Django 2.2.3 on 2019-07-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('work_address', models.CharField(max_length=256)),
                ('tc', models.CharField(max_length=11)),
                ('gsm', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Person')),
            ],
            bases=('api.person',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Person')),
                ('email', models.CharField(max_length=50)),
            ],
            bases=('api.person',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=5)),
                ('home_number', models.CharField(max_length=5)),
                ('room_number', models.CharField(max_length=5)),
                ('size', models.FloatField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.LandLord')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lease_price', models.FloatField()),
                ('dues', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Room')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Guarantor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Tenant')),
            ],
        ),
    ]
