# Generated by Django 2.2.3 on 2019-07-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190710_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Landlord'),
        ),
    ]
