# Generated by Django 2.2.4 on 2019-10-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190710_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=50)),
                ('address_neighborhood', models.CharField(max_length=50)),
                ('address_district', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='agreement',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Guarantor'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Room'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tenant'),
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agreement'),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Landlord'),
        ),
    ]
