# Generated by Django 3.0 on 2019-12-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191215_1823'),
        ('api', '0011_auto_20191215_1816'),
    ]

    operations = [
    ]
