# Generated by Django 3.0 on 2019-12-22 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20191222_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'İnternet Erişim Kodu', 'verbose_name_plural': 'İnternet Erişim Kodları'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expire_in',
            field=models.IntegerField(default=8760, verbose_name='İnternet Erişim Kodu Süresi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 22, 19, 9, 25, 766746, tzinfo=utc), verbose_name='Son Kullanma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Veriliş Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='given_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Landlord'),
        ),
    ]
