# Generated by Django 3.0 on 2019-12-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expired_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Landlord'),
        ),
    ]
