# Generated by Django 3.0 on 2019-12-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191222_1833'),
        ('api', '0016_auto_20191222_1926'),
    ]

    operations = [
    ]
